apiVersion: "networking.k8s.io/v1"
kind: Ingress
metadata:
  name: anywhere-server-ingress
  annotations:
    kubernetes.io/ingress.class: gce
    networking.gke.io/managed-certificates: dev-anywhere-api.seungwoojo.com
    kubernetes.io/ingress.global-static-ip-name: static-ip-dev
    networking.gke.io/v1beta1.FrontendConfig: "http-to-https"
spec:
  defaultBackend:
    service:
      name: anywhere-server-svc
      port:
        number: 80
  rules:
  - http:
      paths:
      - path: ""
        backend:
          service:
            name: anywhere-server-svc
            port:
              number: 80
        pathType: ImplementationSpecific
    host: dev-anywhere-api.seungwoojo.com
status:
  loadBalancer: {}
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: http-to-https
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: dev-anywhere-api.seungwoojo.com
spec:
  domains:
    - dev-anywhere-api.seungwoojo.com
---
# for dev environment, allow only traffic from my home
# remove this when deploying to production
# 
# Create Cloud Armor policy with below commands
# gcloud compute security-policies create policy-allow-only-home --description "whitelisting"
# gcloud compute security-policies rules update 2147483647 --action=deny-403 --security-policy policy-allow-only-home
# gcloud compute security-policies rules create 2 --action=allow --security-policy policy-allow-only-home --description "allow home" --src-ip-ranges "$homeip/32"
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: allow-only-home
spec:
  securityPolicy:
    name: policy-allow-only-home